// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Reason for the status of the case.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum incident_statuscode
    {
        /// <summary>
        /// <para>Assigned To BNET</para>
        /// <para>Value = 167490032</para>
        /// </summary>
        [Description("Assigned To BNET")]
        AssignedToBNET = 167490032,

        /// <summary>
        /// <para>Feedback Returned</para>
        /// <para>Value = 167490031</para>
        /// </summary>
        [Description("Feedback Returned")]
        FeedbackReturned = 167490031,

        /// <summary>
        /// <para>Feedback Verification</para>
        /// <para>Value = 167490030</para>
        /// </summary>
        [Description("Feedback Verification")]
        FeedbackVerification = 167490030,

        /// <summary>
        /// <para>New Case</para>
        /// <para>Value = 167490003</para>
        /// </summary>
        [Description("New Case")]
        NewCase = 167490003,

        /// <summary>
        /// <para>Awaiting response from an internal dept.</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Awaiting response from an internal dept.")]
        AwaitingResponseFromAnInternalDept = 1,

        /// <summary>
        /// <para>Awaiting Operator Acceptance</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Awaiting Operator Acceptance")]
        AwaitingOperatorAcceptance = 3,

        /// <summary>
        /// <para>Awaiting feedback from consumer</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Awaiting feedback from consumer")]
        AwaitingFeedbackFromConsumer = 4,

        /// <summary>
        /// <para>Consumer Affairs Review</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Consumer Affairs Review")]
        ConsumerAffairsReview = 167490000,

        /// <summary>
        /// <para>On Hold - Awaiting consumer consent</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("On Hold - Awaiting consumer consent")]
        OnHoldAwaitingConsumerConsent = 2,

        /// <summary>
        /// <para>On Hold - Awaiting documents/info</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("On Hold - Awaiting documents/info")]
        OnHoldAwaitingDocuments_info = 167490002,

        /// <summary>
        /// <para>Under Process at CAD</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Under Process at CAD")]
        UnderProcessAtCAD = 167490001,

        /// <summary>
        /// <para>Consent Received</para>
        /// <para>Value = 167490006</para>
        /// </summary>
        [Description("Consent Received")]
        ConsentReceived = 167490006,

        /// <summary>
        /// <para>Scope Accepted</para>
        /// <para>Value = 167490008</para>
        /// </summary>
        [Description("Scope Accepted")]
        ScopeAccepted = 167490008,

        /// <summary>
        /// <para>Scope Rejected</para>
        /// <para>Value = 167490009</para>
        /// </summary>
        [Description("Scope Rejected")]
        ScopeRejected = 167490009,

        /// <summary>
        /// <para>Docs/Info. Verified</para>
        /// <para>Value = 167490010</para>
        /// </summary>
        [Description("Docs/Info. Verified")]
        Docs_InfoVerified = 167490010,

        /// <summary>
        /// <para>Under process at internal dept.</para>
        /// <para>Value = 167490011</para>
        /// </summary>
        [Description("Under process at internal dept.")]
        UnderProcessAtInternalDept = 167490011,

        /// <summary>
        /// <para>Under review at CAD</para>
        /// <para>Value = 167490013</para>
        /// </summary>
        [Description("Under review at CAD")]
        UnderReviewAtCAD = 167490013,

        /// <summary>
        /// <para>Feedback</para>
        /// <para>Value = 167490014</para>
        /// </summary>
        [Description("Feedback")]
        Feedback = 167490014,

        /// <summary>
        /// <para>Awaiting Operator Response</para>
        /// <para>Value = 167490015</para>
        /// </summary>
        [Description("Awaiting Operator Response")]
        AwaitingOperatorResponse = 167490015,

        /// <summary>
        /// <para>Rejected by Operator</para>
        /// <para>Value = 167490016</para>
        /// </summary>
        [Description("Rejected by Operator")]
        RejectedByOperator = 167490016,

        /// <summary>
        /// <para>Assigned to Consumer Affairs</para>
        /// <para>Value = 167490017</para>
        /// </summary>
        [Description("Assigned to Consumer Affairs")]
        AssignedToConsumerAffairs = 167490017,

        /// <summary>
        /// <para>Assigned to internal dept.</para>
        /// <para>Value = 167490018</para>
        /// </summary>
        [Description("Assigned to internal dept.")]
        AssignedToInternalDept = 167490018,

        /// <summary>
        /// <para>Insufficient Info/Docs.</para>
        /// <para>Value = 167490019</para>
        /// </summary>
        [Description("Insufficient Info/Docs.")]
        InsufficientInfo_Docs = 167490019,

        /// <summary>
        /// <para>Docs./Info. received</para>
        /// <para>Value = 167490022</para>
        /// </summary>
        [Description("Docs./Info. received")]
        Docs_InfoReceived = 167490022,

        /// <summary>
        /// <para>Settlement Letter Requested</para>
        /// <para>Value = 167490023</para>
        /// </summary>
        [Description("Settlement Letter Requested")]
        SettlementLetterRequested = 167490023,

        /// <summary>
        /// <para>Rejection Rejected</para>
        /// <para>Value = 167490025</para>
        /// </summary>
        [Description("Rejection Rejected")]
        RejectionRejected = 167490025,

        /// <summary>
        /// <para>Feedback received</para>
        /// <para>Value = 167490027</para>
        /// </summary>
        [Description("Feedback received")]
        FeedbackReceived = 167490027,

        /// <summary>
        /// <para>On Hold - Awaiting QOS data</para>
        /// <para>Value = 167490028</para>
        /// </summary>
        [Description("On Hold - Awaiting QOS data")]
        OnHoldAwaitingQOSData = 167490028,

        /// <summary>
        /// <para>Fixed Probs data received</para>
        /// <para>Value = 167490029</para>
        /// </summary>
        [Description("Fixed Probs data received")]
        FixedProbsDataReceived = 167490029,

        /// <summary>
        /// <para>Resolution Provided</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Resolution Provided")]
        ResolutionProvided = 5,

        /// <summary>
        /// <para>Forced Closure</para>
        /// <para>Value = 1000</para>
        /// </summary>
        [Description("Forced Closure")]
        ForcedClosure = 1000,

        /// <summary>
        /// <para>Suggestion Processed</para>
        /// <para>Value = 167490004</para>
        /// </summary>
        [Description("Suggestion Processed")]
        SuggestionProcessed = 167490004,

        /// <summary>
        /// <para>Enquiry Answered</para>
        /// <para>Value = 167490005</para>
        /// </summary>
        [Description("Enquiry Answered")]
        EnquiryAnswered = 167490005,

        /// <summary>
        /// <para>Archived</para>
        /// <para>Value = 167490026</para>
        /// </summary>
        [Description("Archived")]
        Archived = 167490026,

        /// <summary>
        /// <para>Insufficient Documents</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Insufficient Documents")]
        InsufficientDocuments = 6,

        /// <summary>
        /// <para>Duplicate Case</para>
        /// <para>Value = 2000</para>
        /// </summary>
        [Description("Duplicate Case")]
        DuplicateCase = 2000,

        /// <summary>
        /// <para>Cancelled by consumer</para>
        /// <para>Value = 167490021</para>
        /// </summary>
        [Description("Cancelled by consumer")]
        CancelledByConsumer = 167490021,

        /// <summary>
        /// <para>Not in TRA scope</para>
        /// <para>Value = 167490024</para>
        /// </summary>
        [Description("Not in TRA scope")]
        NotInTRAScope = 167490024,
    }
}
