// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Stage of the resolution process for the case.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum incident_incidentstagecode
    {
        /// <summary>
        /// <para>Default Value</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Default Value")]
        DefaultValue = 1,
    }
}
