// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Information that specifies the type of case.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum incident_casetypecode
    {
        /// <summary>
        /// <para>Complaint</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Complaint")]
        Complaint = 1,

        /// <summary>
        /// <para>Enquiry</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Enquiry")]
        Enquiry = 2,

        /// <summary>
        /// <para>Suggestion</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Suggestion")]
        Suggestion = 3,
    }
}
