// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Status of the case.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum incident_statecode
    {
        /// <summary>
        /// <para>Active</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Active")]
        Active = 0,

        /// <summary>
        /// <para>Resolved</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Resolved")]
        Resolved = 1,

        /// <summary>
        /// <para>Canceled</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Canceled")]
        Canceled = 2,
    }
}
