// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Information that specifies the source of the case information, such as Web, telephone, or email.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum incident_caseorigincode
    {
        /// <summary>
        /// <para>Tawasul</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Tawasul")]
        Tawasul = 6,

        /// <summary>
        /// <para>Chatbot</para>
        /// <para>Value = 7</para>
        /// </summary>
        [Description("Chatbot")]
        Chatbot = 7,

        /// <summary>
        /// <para>Call Center</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Call Center")]
        CallCenter = 1,

        /// <summary>
        /// <para>Web Portal</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Web Portal")]
        WebPortal = 3,

        /// <summary>
        /// <para>Email</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Email")]
        Email = 2,

        /// <summary>
        /// <para>eFax</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("eFax")]
        eFax = 4,

        /// <summary>
        /// <para>Mobile App</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Mobile App")]
        MobileApp = 5,
    }
}
