// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Response level for the case. The response level corresponds to the level of service specified in the contract.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum incident_contractservicelevelcode
    {
        /// <summary>
        /// <para>Gold</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Gold")]
        Gold = 1,

        /// <summary>
        /// <para>Silver</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Silver")]
        Silver = 2,

        /// <summary>
        /// <para>Bronze</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Bronze")]
        Bronze = 3,
    }
}
