// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// The service process stage that this entity is in.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum servicestage
    {
        /// <summary>
        /// <para>Identify</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Identify")]
        Identify = 0,

        /// <summary>
        /// <para>Research</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Research")]
        Research = 1,

        /// <summary>
        /// <para>Resolve</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Resolve")]
        Resolve = 2,
    }
}
