// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Post message type private or direct.
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum socialactivity_postmessagetype
    {
        /// <summary>
        /// <para>Public Message</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Public Message")]
        PublicMessage = 0,

        /// <summary>
        /// <para>Private Message</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Private Message")]
        PrivateMessage = 1,
    }
}
