// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Denotes the entity that requested for additional information
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_inforequestedby
    {
        /// <summary>
        /// <para>Consumer Affairs</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Consumer Affairs")]
        ConsumerAffairs = 1,

        /// <summary>
        /// <para>Internal Department</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Internal Department")]
        InternalDepartment = 2,
    }
}
