// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_contractduration
    {
        /// <summary>
        /// <para>No Commitment</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("No Commitment")]
        NoCommitment = 167490000,

        /// <summary>
        /// <para>6 months</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("6 months")]
        _6Months = 167490001,

        /// <summary>
        /// <para>12 months</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("12 months")]
        _12Months = 167490002,

        /// <summary>
        /// <para>18 months</para>
        /// <para>Value = 167490003</para>
        /// </summary>
        [Description("18 months")]
        _18Months = 167490003,

        /// <summary>
        /// <para>24 months</para>
        /// <para>Value = 167490004</para>
        /// </summary>
        [Description("24 months")]
        _24Months = 167490004,

        /// <summary>
        /// <para>30 months</para>
        /// <para>Value = 167490005</para>
        /// </summary>
        [Description("30 months")]
        _30Months = 167490005,

        /// <summary>
        /// <para>36 months</para>
        /// <para>Value = 167490006</para>
        /// </summary>
        [Description("36 months")]
        _36Months = 167490006,

        /// <summary>
        /// <para>Other</para>
        /// <para>Value = 167490007</para>
        /// </summary>
        [Description("Other")]
        Other = 167490007,
    }
}
