// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// The subscription type
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_subscriptiontype
    {
        /// <summary>
        /// <para>Prepaid</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Prepaid")]
        Prepaid = 167490000,

        /// <summary>
        /// <para>Postpaid</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Postpaid")]
        Postpaid = 167490001,
    }
}
