// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Flag showing whether scope was accepted or rejected by call center
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_scopeacceptance
    {
        /// <summary>
        /// <para>Pending</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Pending")]
        Pending = 3,

        /// <summary>
        /// <para>Accepted</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Accepted")]
        Accepted = 1,

        /// <summary>
        /// <para>Rejected</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Rejected")]
        Rejected = 2,
    }
}
