// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_vasrecurrence
    {
        /// <summary>
        /// <para>Once Off</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Once Off")]
        OnceOff = 167490000,

        /// <summary>
        /// <para>Daily</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Daily")]
        Daily = 167490001,

        /// <summary>
        /// <para>Weekly</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("Weekly")]
        Weekly = 167490002,

        /// <summary>
        /// <para>Monthly</para>
        /// <para>Value = 167490003</para>
        /// </summary>
        [Description("Monthly")]
        Monthly = 167490003,
    }
}
