// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Flag to show if consumer has provided his consent
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_consentstatus
    {
        /// <summary>
        /// <para>Not Send</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Not Send")]
        NotSend = 3,

        /// <summary>
        /// <para>Received</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Received")]
        Received = 1,

        /// <summary>
        /// <para>Not Received</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Not Received")]
        NotReceived = 2,
    }
}
