// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_operatorslafailed
    {
        /// <summary>
        /// <para>Yes</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Yes")]
        Yes = 0,

        /// <summary>
        /// <para>No</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("No")]
        No = 1,
    }
}
