// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Flag to show if department feedback was received
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_deptfeedbackrdeeceived
    {
        /// <summary>
        /// <para>Yes</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Yes")]
        Yes = 1,

        /// <summary>
        /// <para>No</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("No")]
        No = 2,
    }
}
