// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_subscriptionstatus
    {
        /// <summary>
        /// <para>Activated</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Activated")]
        Activated = 167490000,

        /// <summary>
        /// <para>Deactivated</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Deactivated")]
        Deactivated = 167490001,
    }
}
