// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// To denote whether Consumer Affairs accepts or rejects a rejection by Service Provider
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_acceptrejection
    {
        /// <summary>
        /// <para>Accepted</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Accepted")]
        Accepted = 1,

        /// <summary>
        /// <para>Rejected</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Rejected")]
        Rejected = 2,
    }
}
