// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_casestatusforconsumer
    {
        /// <summary>
        /// <para>Active</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Active")]
        Active = 167490000,

        /// <summary>
        /// <para>Closed</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Closed")]
        Closed = 167490001,

        /// <summary>
        /// <para>Rejected</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("Rejected")]
        Rejected = 167490002,
    }
}
