// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Field to state whether a consumer was notified
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_notificationstatus
    {
        /// <summary>
        /// <para>Consumer Notified</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Consumer Notified")]
        ConsumerNotified = 167490000,

        /// <summary>
        /// <para>Consumer Unreachable</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Consumer Unreachable")]
        ConsumerUnreachable = 167490001,
    }
}
