// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_subtypeissue
    {
        /// <summary>
        /// <para>Post Termination Charges</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Post Termination Charges")]
        PostTerminationCharges = 167490000,

        /// <summary>
        /// <para>Bad Debt</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Bad Debt")]
        BadDebt = 167490001,

        /// <summary>
        /// <para>Value Added Services</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("Value Added Services")]
        ValueAddedServices = 167490002,

        /// <summary>
        /// <para>Awareness &amp; Knowledge</para>
        /// <para>Value = 167490003</para>
        /// </summary>
        [Description("Awareness & Knowledge")]
        AwarenessKnowledge = 167490003,

        /// <summary>
        /// <para>No Service Charges</para>
        /// <para>Value = 167490005</para>
        /// </summary>
        [Description("No Service Charges")]
        NoServiceCharges = 167490005,

        /// <summary>
        /// <para>Others</para>
        /// <para>Value = 167490004</para>
        /// </summary>
        [Description("Others")]
        Others = 167490004,
    }
}
