// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Flag denotes whether information was requested by CA or Departments
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_informationrequested
    {
        /// <summary>
        /// <para>Yes</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Yes")]
        Yes = 167490000,

        /// <summary>
        /// <para>No</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("No")]
        No = 167490001,
    }
}
