// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// Consumer Satisfaction Level
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_satisfactionlevel
    {
        /// <summary>
        /// <para>Satisfied / راضي</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Satisfied / راضي")]
        Satisfied_راضي = 167490001,

        /// <summary>
        /// <para>Neutral / محايد</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("Neutral / محايد")]
        Neutral_محايد = 167490002,

        /// <summary>
        /// <para>Dissatisfied / غير راضي</para>
        /// <para>Value = 167490003</para>
        /// </summary>
        [Description("Dissatisfied / غير راضي")]
        Dissatisfied_غيرراضي = 167490003,
    }
}
