// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_incident_tra_tra_reasonofrej
    {
        /// <summary>
        /// <para>--Select--</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("--Select--")]
        Select = 2,

        /// <summary>
        /// <para>No complaint raised</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("No complaint raised")]
        NoComplaintRaised = 0,

        /// <summary>
        /// <para>In progress with service provider</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("In progress with service provider")]
        InProgressWithServiceProvider = 1,
    }
}
