// <auto-generated />

using System.CodeDom.Compiler;
using System.ComponentModel;
namespace TRA_MobileAPIs.ProxyClasses.Enums
{
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("XrmToolkit", "7.3.5.0")]
    public enum tra_subtypeissuecontract
    {
        /// <summary>
        /// <para>Device Subsidy</para>
        /// <para>Value = 167490000</para>
        /// </summary>
        [Description("Device Subsidy")]
        DeviceSubsidy = 167490000,

        /// <summary>
        /// <para>Service Activation</para>
        /// <para>Value = 167490001</para>
        /// </summary>
        [Description("Service Activation")]
        ServiceActivation = 167490001,

        /// <summary>
        /// <para>Change of Package Types &amp; Details</para>
        /// <para>Value = 167490002</para>
        /// </summary>
        [Description("Change of Package Types & Details")]
        ChangeOfPackageTypesDetails = 167490002,

        /// <summary>
        /// <para>Contract Renewal</para>
        /// <para>Value = 167490003</para>
        /// </summary>
        [Description("Contract Renewal")]
        ContractRenewal = 167490003,

        /// <summary>
        /// <para>Discount,Offers &amp; Promotions</para>
        /// <para>Value = 167490005</para>
        /// </summary>
        [Description("Discount,Offers & Promotions")]
        DiscountOffersPromotions = 167490005,

        /// <summary>
        /// <para>Others</para>
        /// <para>Value = 167490007</para>
        /// </summary>
        [Description("Others")]
        Others = 167490007,
    }
}
